name: Chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ingore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-REN-2-1-chocolatine-maxence.largeot.git
  EXECUTABLES: pushswap

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - run: check.sh $(pwd) $(pwd)
      - run: |
        FILENAME=coding-style-reports.log
        if [ ! -s "${FILENAME}" ]; then
          echo "File empty"
        else
          while IFS=$'\n'; read line
          do
            TEMP=$(echo $line)
            echo ::error $TEMP
          done < "${FILENAME}"
        fi

##  check_program_compilation:
##    runs-on: ubuntu-latest
##    container: epitechcontent/epitest-docker
##    uses: actions/checkout@v3
##    needs: check_coding_style
##    steps:
##      - run: make
##        timeout-minutes: 2
##      - run: make clean
##    
##
##  run_tests:
##    runs-on: ubuntu-latest
##    container: epitechcontent/epitest-docker
##    uses: actions/checkout@v3
##    needs: check_program_compilation
##    steps:
##
##  push_to_mirror:
##    runs-on: ubuntu-latest
##    uses: actions/checkout@v3
##    needs: run_tests
##    steps: